name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/blog/blog_backend
            git pull
            npm install --force --global ts-node
            npm install --force --global typescript
            npm install --force --global yarn
            yarn install
            pm2 restart blog_backend || pm2 start ./start.sh --name blog_backend
            pm2 restart backend_staging || pm2 start ./start_staging.sh --name backend_staging
